---
- name: Set NTP servers
  bigip_device_ntp:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    ntp_servers:
      - "0.pool.ntp.org"
      - "1.pool.ntp.org"
      - "2.pool.ntp.org"
      - "3.pool.ntp.org"
    state: "{{ state }}"
    validate_certs: "no"
  delegate_to: localhost
...
