---
- name: Set NTP servers
  bigip_device_ntp:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    ntp_servers: "{{ item.ntp_server }}"
    state: "{{ state }}"
    validate_certs: "no"
  delegate_to: localhost
  with_items: "{{ ntp_servers }}"
...
