---
- name: Change admin password
  bigip_user:
    user: "admin"
    password: "{{ bigip_default_admin_password }}"
    server: "{{ inventory_hostname }}"
    username_credential: "admin"
    password_credential: "{{ ansible_password }}"
    validate_certs: "no"

  delegate_to: localhost

- name: Change root password
  bigip_user:
    server: "{{ inventory_hostname }}"
    user: "{{ ansible_username }}"
    password: "{{ ansible_password }}"
    username_credential: root
    password_credential: "{{ ansible_password }}"
    validate_certs: no
  delegate_to: localhost
...
