---
- name: Change admin password
  bigip_user:
    user: "admin"
    password: "admin"
    server: "{{ ansible_host }}"
    username_credential: "admin"
    password_credential: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost

- name: Change root password
  bigip_user:
    server: "{{ inventory_hostname }}"
    user: "{{ ansible_username }}"
    password: "{{ ansible_password }}"
    username_credential: root
    password_credential: "{{ password }}"
    validate_certs: no
  delegate_to: localhost
...
