---
- include_tasks: bigip_user/change_default_passwords.yml
  tags: defaultpw

- include_tasks: bigip_license/license.yaml
  tags: license

- include_tasks: bigip_vlan/add_untagged_vlan.yml
  vars:
    vlans:
      - { name: "vlan_1_2", untagged_interface: "1.2" }
      - { name: "vlan_1_3", untagged_interface: "1.3" }
  tags: vlan

- include_tasks: bigip_device_ntp/set_ntp_server.yml
  tags: ntp
...
