---
- include_tasks: bigip_vlan/add_untagged_vlan.yml 
  vars: 
    servers:
      - { name: "vlan_1_3", untagged_interface: "1.2" }
      - { name: "vlan_1_4", untagged_interface: "1.2" }
      - { name: "vlan_1_5", untagged_interface: "1.2" }
      - { name: "vlan_1_6", untagged_interface: "1.2" }
      - { name: "vlan_1_7", untagged_interface: "1.2" }
      - { name: "vlan_1_8", untagged_interface: "1.2" }
      - { name: "vlan_1_9", untagged_interface: "1.2" }
      - { name: "vlan_1_10", untagged_interface: "1.2" }
      - { name: "vlan_1_11", untagged_interface: "1.2" }
      - { name: "vlan_1_12", untagged_interface: "1.2" }
      - { name: "vlan_1_13", untagged_interface: "1.2" }
...
