---
- include_tasks: bigip_vlan/add_untagged_vlan.yml 
  vars: 
    vlans:
      - { name: "vlan_1_3", untagged_interface: "1.3" }
      - { name: "vlan_1_4", untagged_interface: "1.4" }
      - { name: "vlan_1_5", untagged_interface: "1.5" }
      - { name: "vlan_1_6", untagged_interface: "1.6" }
      - { name: "vlan_1_7", untagged_interface: "1.7" }
      - { name: "vlan_1_8", untagged_interface: "1.8" }
      - { name: "vlan_1_9", untagged_interface: "1.9" }
      - { name: "vlan_1_10", untagged_interface: "1.10" }
      - { name: "vlan_1_11", untagged_interface: "1.11" }
      - { name: "vlan_1_12", untagged_interface: "1.12" }
      - { name: "vlan_1_13", untagged_interface: "1.13" }
  tags: vlan

- include_tasks: bigip_device_ntp/set_ntp_server.yml 
  vars: 
    ntp_servers:
      - { ntp_server: "0.pool.ntp.org" }
      - { ntp_server: "1.pool.ntp.org" }
      - { ntp_server: "2.pool.ntp.org" }
      - { ntp_server: "3.pool.ntp.org" }
  tags: ntp
...
