---
- name: Add untagged VLAN to interface "{{ untagged_interface }}" 
  bigip_vlan:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    name: "{{ item.name }}"
    untagged_interface: "{{ item.untagged_interface |default(omit) }}" 
    state: "{{ state }}"
    validate_certs: "no"
  delegate_to: localhost
  with_items: "{{ vlans }}"
...
